spring:
  profiles:
    active:
    - dev
---
server:
  port: 8761	# 端口
spring:
  profiles: dev
  application:
    name: config-client
eureka:
  instance:
    hostname: eureka-server  # eureka实例的主机名
  client:
    register-with-eureka: false # 不把自己注册到eureka上
    fetch-registry: false # 不从eureka上来获取服务的注册信息
    service-url:
      defaultZone: http://localhost:8761/eureka/
---
server:
  port: 8762	# 端口
spring:
  profiles: test
  application:
    name: config-client
eureka:
  instance:
    hostname: eureka-server  # eureka实例的主机名
  client:
    register-with-eureka: false # 不把自己注册到eureka上
    fetch-registry: false # 不从eureka上来获取服务的注册信息
    service-url:
      defaultZone: http://localhost:8762/eureka/
