spring:
  profiles:
    active:
    - dev
---
server:
  port: 80
spring:
  profiles: test
  application:
    name: config-client-80
eureka:
  instance:
    prefer-ip-address: true # 注册服务的时候使用服务的ip地址
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/  	# 注册中心地址
# 开启Feign支持Hystrix
feign:
  hystrix:
    enabled: true

---
server:
  port: 82
spring:
  profiles: dev
  application:
    name: config-client-82
eureka:
  instance:
    prefer-ip-address: true # 注册服务的时候使用服务的ip地址
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8762/eureka/  	# 注册中心地址
# 开启Feign支持Hystrix
feign:
  hystrix:
    enabled: true
